spring:
  datasource:
    url: "${DB_URL}"
    username: ${DB_USER}
    password: "${DB_PASS}"
  data:
    redis:
      host: ${RD_HOST}
      port: ${RD_PORT}
      username: default
      password: "${RD_PASS}"
      ssl:
        enabled: true


  security:
    oauth2:
      client:
        registration:
          google:
            # Thay localhost báº±ng IP Azure
            redirect-uri: "http://70.153.80.120:8080/api/v1/authenticate"

payment:
  vnPay:
    returnUrl: "https://auction-ct03.netlify.app//payment-result"